spring:
  application:
    name: ludotheque
  config:
    import: optional:file:./secrets.yml
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    #driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create


JWT:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629